const types = {
    START_CHANNEL: 'START_CHANNEL',
    STOP_CHANNEL: 'STOP_CHANNEL',
    CHANNEL_ON: 'CHANNEL_ON',
    CHANNEL_OFF: 'CHANNEL_OFF',
    SERVER_ON: 'SERVER_ON',
    SERVER_OFF: 'SERVER_OFF',

    INIT_SOCKET_CONNECTION: 'INIT_SOCKET_CONNECTION',

    ADD_MESSAGE_START: 'ADD_MESSAGE_START',
    ADD_MESSAGE_SUCCESS: 'ADD_MESSAGE_SUCCESS',
    ADD_MESSAGE_ERROR: 'ADD_MESSAGE_ERROR',

    SELECT_CURRENT_ROOM_START: 'SELECT_CURRENT_ROOM_START',
    SELECT_CURRENT_ROOM_SUCCESS: 'SELECT_CURRENT_ROOM_SUCCESS',
    SELECT_CURRENT_ROOM_FAILURE: 'SELECT_CURRENT_ROOM_FAILURE',

    GET_ROOM_MESSAGES_START: 'GET_ROOM_MESSAGES_START',
    GET_ROOM_MESSAGES_SUCCESS: 'GET_ROOM_MESSAGES_SUCCESS',
    GET_ROOM_MESSAGES_FAILURE: 'GET_ROOM_MESSAGES_FAILURE',

    LEAVE_ROOM_START: 'LEAVE_ROOM_START',
    LEAVE_ROOM_SUCCESS: 'LEAVE_ROOM_SUCCESS',
    LEAVE_ROOM_FAILURE: 'LEAVE_ROOM_FAILURE',

    INIT_ROOM_START: 'INIT_ROOM_START',
    INIT_ROOM_SUCCESS: 'INIT_ROOM_SUCCESS',
    INIT_ROOM_FAILURE: 'INIT_ROOM_FAILURE',

    GET_ROOMS_START: 'GET_ROOMS_START',
    GET_ROOMS_SUCCESS: 'GET_ROOMS_SUCCESS',
    GET_ROOMS_FAILURE: 'GET_ROOMS_FAILURE',

    GET_SYSTEM_CONTACTS_START: 'GET_SYSTEM_CONTACTS_START',
    GET_SYSTEM_CONTACTS_SUCCESS: 'GET_SYSTEM_CONTACTS_SUCCESS',
    GET_SYSTEM_CONTACTS_FAILURE: 'GET_SYSTEM_CONTACTS_FAILURE'
};

export default types;