const types = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',


  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

  EDIT_USER_START: 'EDIT_USER_START',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_FAILURE: 'EDIT_USER_FAILURE',

  CHANGE_ONLINE_START: 'CHANGE_ONLINE_START',
  CHANGE_ONLINE_SUCCESS: 'CHANGE_ONLINE_SUCCESS',
  CHANGE_ONLINE_FAILURE: 'CHANGE_ONLINE_FAILURE',

  SET_TOKENS_START: 'SET_TOKENS_START',
  SET_TOKENS_SUCCESS: 'SET_TOKENS_SUCCESS',
  SET_TOKENS_ERROR: 'SET_TOKENS_SUCCESS'
};

export default types;
